apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "web"
  namespace: "default"
spec:
  backend:
    serviceName: "web"
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: json
spec:
  ports:
    - port: 80
  selector:
    app: json
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: json
spec:
  selector:
    matchLabels:
      app: json
      tier: backend
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: json
        tier: backend
    spec:
      containers:
      - name: web
        image:  mtahle/apache:1.0 
        readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30 
            periodSeconds: 60
        livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15 
            periodSeconds: 65
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web